liip_imagine:
  filter_sets:
      thumb:
          quality: 85
          filters:
              thumbnail:
                  size: [360,200]
                  mode: outbound

      medium:
          quality: 85
          filters:
              thumbnail:
                  size: [800,530]
                  mode: outbound

      bandeau:
          quality: 100
          filters:
              thumbnail:
                  size: [1920,500]
                  mode: outbound